# Generated by Django 4.0.4 on 2022-06-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_category_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielinks',
            name='type',
            field=models.CharField(choices=[('W', 'WATCH LINK'), ('D', 'DOWNLOAD LINK')], max_length=1),
        ),
    ]
