# Generated by Django 4.0.4 on 2022-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movielinks_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Movielinks',
        ),
    ]
