# Generated by Django 4.0.4 on 2022-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_alter_movielinks_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielinks',
            name='type',
            field=models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], max_length=1),
        ),
    ]
